### PR TITLE
whoami = pr

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by niklassiemer** [comment]
@pyiron/pyiron
FYI: GitHub tests against the __merged__ PR as you may see here. Only if you check out the HEAD of one specific branch (like I do in the TestBranch workflow) the tests are performed on the specific branch only.

**Comment by niklassiemer** [comment]
Since pyiron/pyiron did not seem to work:
@jan-janssen @muh-hassani @pmrv @samwaseda @Ahmed-Aslam @sudarsan-surendralal @liamhuber

**Comment by niklassiemer** [comment]
To quickly explain the setup:
- in master `whoami` is set to `master`  and `pr` is expected (fail of CI, see master commit 8e6ee60131ce66ea91e72d0ff3ffbc260293c0b9)
- in test_checkout `whoami` is set to `pr` and `master` is expected (fail of CI: TestBranch/build)
- In the merged result both would be `pr` and CI passes (Python package/build)

**Comment by jan-janssen** [comment]
I am surprised but that means Github is already more intelligent than I expected as they automatically try to merge. But then I still do not understand why the pull request on pyiron worked and the master branch broke after merging. This is only possible when the pull request was executed in comparison to an older version of the master branch and then the master branch was updated in the meantime without executing the tests again, so the merge request which was tested in comparison to an older version of the master branch should have been tested again after updating the master branch.

**Comment by sudarsan-surendralal** [comment]
Nice demo @niklassiemer! This was really helpful.

**Pull request closed without merging**
